#vi appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/mubin/devopspipeline
permissions:
  - object: scripts/
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root #root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root #mubin