version: 0.2
phases:
  install:
    commands:
      - echo "the installation phase begins"
  pre_build:
    commands:
      - echo "the prebuild phase begins"
      - cd client
      - ls -la
      - echo "Checking network connectivity..."
      - curl -I https://github.com || (echo "Network connectivity issue" && exit 1)
      - echo "Network check complete. Configuring npm registry..."
      - npm config set registry https://registry.npmjs.org/
      - npm install
  build:
    commands:
      - echo "the build phase begins"
      - npm run build
  post_build:
    commands:
      - echo "the post build phase. navigating back to root path"
      - cp -R build/ ../

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - buildspec.yml
    - server/**/*
    - client/**/*
    - nginx/*
    - scripts/*
    - docker-compose.yml
    - Dockerfile
    - nginx.conf
