version: "3.3"
services:
  nginx_app:
    container_name: nginx_app
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always

  inotebook:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always

  mongo_db:
    container_name: mongo_db
    image: mongo
    volumes:
      - mongo_volume:/data/db
    ports:
      - 27017:27017

  server:
    container_name: server_service
    build:
      context: ./server
      dockerfile: Dockerfile
    command: nodemon index.js
    ports:
      - 5000:5000
    depends_on:
      - mongo_db

volumes:
  mongo_volume:
