#vi docker-compose.yml
version: "3.3"
services:
  nginx_app:
    container_name: nginx_app
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always

  inotebook:
    container_name: node_app
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm start
    restart: always
    expose:
      - 3001
    ports:
      - 3002:3001
    links:
      - mongo_db

  mongo_db:
    container_name: mongo_db
    image: mongo
    volumes:
      - /mongodbvolume:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

#volumes:
# - /mongodbvolume:/data/db
#jdjff